shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node 5
  - npm install
build: off
test_script: node --harmony_rest_parameters test.js
cache: node_modules -> package.json
